name: Compile

on:
  push:
jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      run: | 
        cd WhatAboutSAM; cd WhatAboutSAM; cl Main.cpp /Fe:WhatAboutSam /std:c++14
    - name: run
      run: |
        WhatAboutSam.exe
      shell: cmd
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          WhatAboutSam.exe
